version: '3'
services:
  place:
    build:
      dockerfile: ./docker/app.dockerfile
      context: .
    image: pontalti/place
    container_name: place
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      - production-network

networks:
  production-network:
    driver: bridge