services:
    place:
        build:
            dockerfile: ./src/main/docker/Dockerfile.jvm
            context: .
        image: pontalti/place
        container_name: place
        ports:
          - "8080:8080"
          - "8000:8000"
        networks: 
            - production-network
            
networks: 
    production-network:
        driver: bridge
