FROM gradle:jdk25-alpine AS build

WORKDIR /home/app

COPY gradlew .
COPY gradle ./gradle
COPY settings.gradle.kts gradle.properties build.gradle.kts  ./

RUN chmod +x ./gradlew

COPY src ./src

RUN ./gradlew clean build --no-daemon


FROM eclipse-temurin:25-jre-alpine

WORKDIR /app

COPY --from=build /home/app/build/quarkus-app/ ./

EXPOSE 8080 8000

CMD ["java", "-jar", "quarkus-run.jar"]